#!/bin/bash


find airborn marketplace firetext | grep \.git[^/]*$ | sed -e 'p;s/.git/git/' | xargs -n2 mv &&
git add -A airborn marketplace firetext &&
find airborn marketplace firetext | grep git[^/]*$ | xargs git reset HEAD &&
git commit -qm "Update airborn" &&
find airborn marketplace firetext | grep git[^/]*$ | sed -e 'p;s/git/.git/' | xargs -n2 mv &&
(
	git push -qf heroku master
	git reset -q HEAD^
)