#!/bin/bash

airborn_src=`[ $1 ] && echo file://$(readlink -m $1) || echo https://github.com/twiss/airborn.git`
marketplace_src=`[ $2 ] && echo file://$(readlink -m $2) || echo https://github.com/twiss/airborn-marketplace-app.git`

(
	echo Updating Airborn from $airborn_src
	rm -rf airborn &&
	git clone -q --depth 1 $airborn_src airborn
) &&
(
	echo Updating Marketplace from $marketplace_src
	rm -rf marketplace &&
	git clone -q --depth 1 $marketplace_src marketplace
)